eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka

server:
  port: 8077

spring:
  application:
    name: school
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school
    hikari:
      username: root
      password: BINDE5243
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
application:
  config:
    students-url: http://localhost:8222/api/v1/students

management:
      tracing:
        sampling:
          probability: 1.0