eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka

server:
  port: 8099

spring:
  application:
    name: students
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/students
    hikari:
      username: root
      password: BINDE5243
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
